name: Build & Deploy React App to Azure

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application (Vite)
        run: |
          npm run build | tee build-log.txt
          if [ ! -d "dist" ]; then
            echo "❌ Error: 'dist' folder not found. Build failed!"
            exit 1
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build-log.txt

  deploy:
    name: Deploy to Azure Web App
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./dist

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MyReactAzureDemoApp'  # <-- Change to your Azure app name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './dist'
