name: 🚀 Auto PR to dev + Auto-Merge on Approvals

on:
  push:
    branches:
      - 'feature/*'

jobs:
  auto_pr:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout current branch
        uses: actions/checkout@v3

      - name: 🛠 Create PR to dev
        id: pr_create
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          script: |
            const currentBranch = context.ref.replace('refs/heads/', '');
            const { data: pull } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `✨ PR from ${currentBranch}`,
              head: currentBranch,
              base: 'dev',
              body: `🚀 This PR was auto-created from \`${currentBranch}\``
            });

            console.log("Pull Request Created: #" + pull.number);
            return pull.number;

      - name: ✅ Enable Auto-Merge (after approval)
        if: steps.pr_create.outputs.result != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          script: |
            const prNum = parseInt('${{ steps.pr_create.outputs.result }}');
            const pullData = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNum
            });

            const nodeId = pullData.data.node_id;

            await github.graphql(`
              mutation EnableAutoMerge($id: ID!) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $id,
                  mergeMethod: SQUASH
                }) {
                  pullRequest {
                    number
                    autoMergeRequest {
                      enabledAt
                    }
                  }
                }
              }
            `, {
              id: nodeId
            });

            console.log("Auto-Merge enabled for PR #" + prNum);
